### ISSUE TITLE
issue with webpack + ES6/babel and sourceMaps

### ISSUE THREAD

**Issue by revolunet** [webpack-contrib/transform-loader#9]
Hey!

When using transform-loader with babel looks like it breaks the source maps.

Here's my config : 

``` js
loaders: [{
    test: /\.(js|es6|jsx)$/,
    exclude: /node_modules/,
    loaders: [
        'transform/cacheable?brfs',
        'babel'
    ]
}]
```

when `transform` enabled, chrome directs me to the ES5 transpiled code.
if i comment the line, i have the correct sources in chrome.

any idea how to fix this ?

Thanks!

**Comment by revolunet** [comment]
(tried with `devtool: 'eval-source-map',` and every other option without luck)

**Comment by sokra** [comment]
This doesn't work for two reasons:
* brfs doesn't emit SourceMaps
* transform-loader doesn't support input SourceMaps (nested SourceMap)

**Comment by revolunet** [comment]
Thanks for the feedback ! so is there any way to fix this ?

when using browserify/brfs i think i had the sourcemaps working;

**Comment by sokra** [comment]
> when using browserify/brfs i think i had the sourcemaps working;

I tried it again, but `brfs` doesn't emit a SourceMap. `coffeeify` does.

**Comment by revolunet** [comment]
ok thanks man!

**Comment by thaiat** [comment]
for a quick and dirty workaround: https://github.com/thaiat/webpack-babel-sourcemap

**Comment by steveinatorx** [comment]
@thaiat solution worked for me ! move babel to the first loader and add a query block

`module: {
    loaders: [{
      test: /\.js$/,
      loader: 'babel',
      exclude: /node_modules/,
      include: __dirname,
      query: {
        retainLines: true,
        cacheDirectory: true
      }
    }]`
